version: 2.1

executors:
  go-executor:
    docker:
      - image: circleci/golang:1.20

jobs:
  test:
    executor: go-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: go mod tidy
      - run:
          name: Run Tests and Generate JUnit Report
          command: make test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

workflows:
  version: 2
  test:
    jobs:
      - test
